"""
Gold layer validation tests — reads outputs/CSV exports, no Spark required.
Requires: outputs/borough_priority_ranking.csv to exist (generated by notebook 05).
"""

from pathlib import Path

import pandas as pd
import pytest

OUTPUTS = Path(__file__).resolve().parents[1] / "outputs"


def csv(name):
    path = OUTPUTS / name
    if not path.exists():
        pytest.skip(f"{name} not found — run notebook 05 or 07 to generate it")
    return pd.read_csv(path)


class TestBoroughPriority:
    def test_33_boroughs(self):
        df = csv("borough_priority_ranking.csv")
        assert len(df) == 33, f"Expected 33 boroughs, got {len(df)}"

    def test_no_null_borough(self):
        df = csv("borough_priority_ranking.csv")
        assert df["borough"].notna().all()

    def test_rank_range(self):
        df = csv("borough_priority_ranking.csv")
        assert df["priority_rank"].min() == 1
        assert df["priority_rank"].max() <= 33

    def test_pct_below_epc_c_bounds(self):
        df = csv("borough_priority_ranking.csv")
        assert (df["pct_below_epc_c"] >= 0).all()
        assert (df["pct_below_epc_c"] <= 100).all()

    def test_no_duplicate_boroughs(self):
        df = csv("borough_priority_ranking.csv")
        assert df["borough"].nunique() == len(df)


class TestRetrofitScenarios:
    def test_no_null_borough(self):
        df = csv("borough_retrofit_scenarios.csv")
        assert df["borough"].notna().all()

    def test_central_between_optimistic_and_pessimistic(self):
        df = csv("borough_retrofit_scenarios.csv")
        cols = {"per_home_optimistic", "per_home_central", "per_home_pessimistic"}
        if not cols.issubset(df.columns):
            pytest.skip("Expected columns not present")
        assert (df["per_home_optimistic"] <= df["per_home_central"]).all()
        assert (df["per_home_central"] <= df["per_home_pessimistic"]).all()


class TestWallType:
    def test_pct_sums_to_100(self):
        df = csv("borough_wall_type.csv")
        if "pct_solid_wall" not in df.columns or "pct_cavity_wall" not in df.columns:
            pytest.skip("Expected columns not present")
        total = df["pct_solid_wall"] + df["pct_cavity_wall"]
        assert (total.round(0) == 100).all(), "Solid + cavity wall % should sum to 100"
